# Generated by Django 3.1.1 on 2020-09-20 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageanimal',
            options={'verbose_name': 'Фото Питомца', 'verbose_name_plural': 'Фото Питомцев'},
        ),
        migrations.AddField(
            model_name='imageanimal',
            name='animal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='animals.animal', verbose_name='петомец'),
            preserve_default=False,
        ),
    ]
