# Generated by Django 3.1.1 on 2020-09-20 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('animals', '0002_auto_20200920_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='user_profile',
        ),
        migrations.RemoveField(
            model_name='imageanimal',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='animal',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imageanimal',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
