# Generated by Django 3.1.1 on 2020-09-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_auto_20200920_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
